Fixed frame rate not being set
Woodyjl/MWCamera pull request #4
Opened 2019-11-26 10:23 UTC by tkohout

If the desired frame rate is the same as the videoDevice's frame rate the frameRate variable is not being set causing the frame correction logic in `handleVideoBuffer` not function properly

2019-11-29 07:35 UTC, Woodyjl requested changes

2019-11-29 07:35 UTC, Woodyjl commented on MWCamera/Classes/MWBaseCameraViewController.swift
>          guard videoDevice.activeVideoMinFrameDuration.timescale != frameRate,
Although this addition fixes the bug of an uninitialized `self.frameRate` it does reveal another bug. This method is intended to fix the frame rate of videoDevice, but the guard statement will return in a situation where `videoDevice.activeVideoMixFrameDuration.timescale` may not be equal to `videoDevice.activeVideoMaxFrameDuration.timescale`.

Also if the an error is ever thrown in the do statement then `self.frameRate` won't be set as well. Here is snippet of code that solves all problems. let me know what you think.

```
        guard videoDevice.activeVideoMinFrameDuration.timescale != videoDevice.activeVideoMaxFrameDuration.timescale,
            || videoDevice.activeVideoMinFrameDuration.timescale != frameRate else {
                self.frameRate = frameRate
                return
        }

        do {
            try videoDevice.lockForConfiguration()
            videoDevice.activeVideoMinFrameDuration = CMTime.init(value: 1, timescale: CMTimeScale(frameRate))
            videoDevice.activeVideoMaxFrameDuration = CMTime.init(value: 1, timescale: CMTimeScale(frameRate))
            videoDevice.unlockForConfiguration()

            self.frameRate = frameRate
        } catch {
            print("[mwCamera]: Could not lock device for configuration: \(error)")
            self.frameRate = videoDevice.activeVideoMaxFrameDuration.timescale
        }
```

Well our problem is not really solved when the catch statement is evoked(frame rate is not fixed so frame rate logic further down is still open to video/audio sync issues). I'm not sure how I should handle that problem. Suggestions are welcomed 😄 .

2019-11-29 08:17 UTC, Woodyjl commented
@tkohout Once we resolve the changes I brought up I'll go ahead and merge your changes.

2019-12-03 08:24 UTC, tkohout commented
Hello @Woodyjl , thanks for this library is very good learning resource! In the end, we have decided to go in completely different direction and use NextLevel with separate recordings when flipping camera. 

This seems like more broad issue anyway that I don't have enough knowledge about so I think it would be better if you implement the other fixes yourself

2023-05-12 14:05 UTC, closed without merging